localizationDateobs: '2020-08-26T04:29:53'
localizationName: 'glg_healpix_all_bn200826187.fits'
startDate: '2020-08-26 04:29:53'
endDate: '2020-09-02 04:29:53'
localizationCumprob: 0.2
numberDetections: 2
numPerPage: 100
skyportal_token: null
skyportal_url: null
whitelisted: true

  
